FROM python:3.9.10

RUN mkdir /app
WORKDIR /app

COPY requirements.txt /app
COPY . /app

RUN pip install -r requirements.txt

WORKDIR /app/src

EXPOSE 8000
ENTRYPOINT ["poetry", "run", "uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "8000"]
