services:
  backend:
    build:
      dockerfile: ./Dockerfile_backend
      context: .
    ports:
      - "8000:8000"

  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
      context: .
    depends_on:
      - backend
    ports:
      - "3000:3000"